# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: flask-app
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 5000


apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30008
  # type: NodePort
  type: LoadBalancer

  
