apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: vigneshvicky97/flask-guestbook:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"