name: Test and Build

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #Setting up environment
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
          
      # Test the Code
      - name: Run Linting tests
        run: |
          flake8 --ignore=E501,F401 .
      
      - name: Docker Credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker tag
        id: version
        run: |
          VERSION=v$(date +"%Y%m%d%H%M%S")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Build the Docker Image
      - name: Build Docker Image
        run: |
          docker build . -t vigneshvicky97/flask-guestbook:${{ env.VERSION }} 
      
      # Push the Docker Image
      - name: Push Docker Image
        run: |
          docker push vigneshvicky97/flask-guestbook:${{ env.VERSION }}
      
      # UPdate the K8s Manifest Files
      - name: Update K8s Manifests
        run: |
          cat k8s/flask-deployment.yml
          sed -i "s|image: vigneshvicky97/demo-app:.*|image: vigneshvicky97/flask-guestbook:${{ env.VERSION }}|g" k8s/flask-deployment.yml
          cat k8s/flask-deployment.yml

      # Update Github
      - name: Commit the changes
        run: |
          git config --global user.email "<>"
          git config --global user.name "GitHub Actions Bot"
          git add k8s/flask-deployment.yml
          git commit -m "Update k8s/flask-deployment.yml with new image version - ${{ env.VERSION }}"
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/vigneshs-dev/GuestBook.git
          git push origin main

      


        
      
