name: Test and Build

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Setting up environment
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
          
      # Test the Code
      - name: Run Linting tests
        run: |
          flake8 --ignore=E501,F401 .

      # Docker Setup with QEMU (For Multi-Arch)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Authenticate to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Define Docker Image Tag
      - name: Define Image Tag
        id: version
        run: |
          VERSION=v$(date +"%Y%m%d%H%M%S")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Build and Push Multi-Arch Docker Image
      - name: Build and Push Multi-Arch Docker Image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t vigneshvicky97/flask-guestbook:${{ env.VERSION }} .

      # Update K8s Manifests with New Image
      - name: Update K8s Manifests
        run: |
          sed -i "s|image: vigneshvicky97/flask-guestbook:.*|image: vigneshvicky97/flask-guestbook:${{ env.VERSION }}|g" k8s/flask-deployment.yml
          cat k8s/flask-deployment.yml

      # Commit and Push the Updated K8s Manifest
      - name: Commit K8s Manifest Changes
        run: |
          git config --global user.email "<>"
          git config --global user.name "GitHub Actions Bot"
          git add k8s/flask-deployment.yml
          git commit -m "Update k8s/flask-deployment.yml with new multi-arch image version - ${{ env.VERSION }}"
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/vigneshs-dev/GuestBook.git
          git push origin main
